### ISSUE TITLE
tests fail on Windows

### ISSUE THREAD

**Issue by refack** [joyeecheung/node-core-utils#36]
*The three `auth` tests fail (looks like incompatible IPC parsing)
*MetadataGenerator has an unhandled rejection:
  ```
  Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'currentRetry' of undefined
  ```

<details>

```
  auth
    1) asks for auth data if no ncurc is found
    2) asks for auth data if ncurc is invalid json
    3) returns ncurc data if it is present and valid

  CIparser
    √ should parse CI results

  Comparison
    √ should sort by ascending
    √ should sort by descending

  LinkParser
    √ should parse fixes and refs (87ms)

  MetadataGenerator
(node:11352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'currentRetry' of undefined
(node:11352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    √ should generate metadata properly

  PRChecker
    √ should warn if no CI runs detected
    √ should summarize CI runs detected
    √ should check odd commits for first timers

  ReviewAnalyzer
    √ should parse reviews and comments that all approve


  9 passing (758ms)
  3 failing

  1) auth
       asks for auth data if no ncurc is found:

      AssertionError [ERR_ASSERTION]:   # test\unit\auth.test.js:75

  assert.strictEqual(expect.length, 0)
                     |      |
                     |      7
                     ["Reading configuration for node-core-utils failed:",/ENOENT: no such file or directory, open/,"Please enter your Github user information:",/Github tokens can be created as described in/,#Object#,#Object#,"bnlhbmNhdDowMTIzNDU2Nzg5YWJjZGVm"]

      + expected - actual

      -7
      +0

      at Decorator._callFunc (node_modules\empower-core\lib\decorator.js:110:20)
      at Decorator.concreteAssert (node_modules\empower-core\lib\decorator.js:103:17)
      at Function.decoratedAssert [as strictEqual] (node_modules\empower-core\lib\decorate.js:49:30)
      at ChildProcess.proc.on (d:\code\4node\node-core-utils/test\unit\auth.test.js:75:16)
      at maybeClose (internal/child_process.js:927:16)
      at Socket.stream.socket.on (internal/child_process.js:348:11)
      at Pipe._handle.close [as _onclose] (net.js:547:12)

  2) auth
       asks for auth data if ncurc is invalid json:
     Uncaught AssertionError [ERR_ASSERTION]: cmVmYWNrOmY4YzZkNmMyZWNhNDlkOWY1NDYzZTM0ODI3ODA5M2QzODI2ZDFlNTA=
 should match /^Reading configuration for node-core-utils failed:$/   # test\unit\auth.test.js:122

  assert(line.match(expected), `${ line } should match ${ expected }`)
         |    |     |
         |    null  /^Reading configuration for node-core-utils failed:$/
         "cmVmYWNrOmY4YzZkNmMyZWNhNDlkOWY1NDYzZTM0ODI3ODA5M2QzODI2ZDFlNTA=\n"

      at Decorator._callFunc (node_modules\empower-core\lib\decorator.js:110:20)
      at Decorator.concreteAssert (node_modules\empower-core\lib\decorator.js:103:17)
      at decoratedAssert (node_modules\empower-core\lib\decorate.js:49:30)
      at powerAssert (node_modules\empower-core\index.js:63:32)
      at onLine (d:\code\4node\node-core-utils/test\unit\auth.test.js:122:7)
      at Timeout.setTimeout (d:\code\4node\node-core-utils/test\unit\auth.test.js:101:13)

  3) auth
       returns ncurc data if it is present and valid:

      AssertionError [ERR_ASSERTION]:   # test\unit\auth.test.js:75

  assert.strictEqual(expect.length, 0)
                     |      |
                     |      7
                     ["Reading configuration for node-core-utils failed:",/Unexpected token h in JSON at position 1/,"Please enter your Github user information:",/Github tokens can be created as described in/,#Object#,#Object#,"bnlhbmNhdDowMTIzNDU2Nzg5YWJjZGVm"]

      + expected - actual

      -7
      +0

      at Decorator._callFunc (node_modules\empower-core\lib\decorator.js:110:20)
      at Decorator.concreteAssert (node_modules\empower-core\lib\decorator.js:103:17)
      at Function.decoratedAssert [as strictEqual] (node_modules\empower-core\lib\decorate.js:49:30)
      at ChildProcess.proc.on (d:\code\4node\node-core-utils/test\unit\auth.test.js:75:16)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)




d:\code\4node\node-core-utils\node_modules\empower-core\lib\decorator.js:110
        ret = func.apply(thisObj, args);
                   ^
AssertionError [ERR_ASSERTION]: cmVmYWNrOmY4YzZkNmMyZWNhNDlkOWY1NDYzZTM0ODI3ODA5M2QzODI2ZDFlNTA=
 should match /^bnlhbmNhdDowMTIzNDU2Nzg5YWJjZGVm$/   # test\unit\auth.test.js:122

  assert(line.match(expected), `${ line } should match ${ expected }`)
         |    |     |
         |    null  /^bnlhbmNhdDowMTIzNDU2Nzg5YWJjZGVm$/
         "cmVmYWNrOmY4YzZkNmMyZWNhNDlkOWY1NDYzZTM0ODI3ODA5M2QzODI2ZDFlNTA=\n"

    at Decorator._callFunc (d:\code\4node\node-core-utils\node_modules\empower-core\lib\decorator.js:110:20)
    at Decorator.concreteAssert (d:\code\4node\node-core-utils\node_modules\empower-core\lib\decorator.js:103:17)
    at decoratedAssert (d:\code\4node\node-core-utils\node_modules\empower-core\lib\decorate.js:49:30)
    at powerAssert (d:\code\4node\node-core-utils\node_modules\empower-core\index.js:63:32)
    at onLine (d:\code\4node\node-core-utils/test\unit\auth.test.js:122:7)
    at Timeout.setTimeout (d:\code\4node\node-core-utils/test\unit\auth.test.js:101:13)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

</details>

**Comment by joyeecheung** [comment]
Thanks for checking this one out. Travis does not seem to support Windows at the moment..maybe we should add [appveyor](https://www.appveyor.com/) to the mix as well

**Comment by refack** [comment]
I live in Windows 🤷‍♂️ 
I'll fix this and create an AppVeyor config.
