### ISSUE TITLE
`npm run coverage-all` emits an error on Travis CI

### ISSUE THREAD

**Issue by cPhost** [joyeecheung/node-core-utils#87]
It passes locally and on appveyor but emits error on CI.

**Comment by cPhost** [comment]
I need confirmation does `--reporter` shoule be `text-locv`

**Comment by joyeecheung** [comment]
Which build has failed?

**Comment by apapirovski** [comment]
I'm not seeing the errors... Link?

**Comment by cPhost** [comment]
```
> nyc --reporter=lcov --reporter=text --reporter=text-summary npm run test-all

YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/bin/nyc.js:20:54)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/travis/build/joyeecheung/node-core-utils/node_modules/nyc/bin/nyc.js:66:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by joyeecheung** [comment]
@cPhost That's kind of weird, subsequent builds seem to work fine, looks like some nyc internal machineries gone wrong..

**Comment by cPhost** [comment]
I will try to work on it on fork. But i think if that does not work we now have appveyor reporting coverage.

**Comment by cPhost** [comment]
closing this now as it seems there has been no more errors.
