### ISSUE TITLE
latest version is broken

### ISSUE THREAD

**Issue by targos** [joyeecheung/node-core-utils#90]
```console
$ get-metadata 16571
module.js:515
    throw err;
    ^

Error: Cannot find module '../steps/metadata'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mzasso/.nvm/versions/node/v8.8.0/lib/node_modules/node-core-utils/bin/get_metadata.js:5:21)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

**Comment by Tiriel** [comment]
Hey!
Can you give us specifics? Which OS? Which version? How did you install it? (npm, source?)

**Comment by targos** [comment]
Installed with `npm install -g node-core-utils` on Linux x64.

Contents of the package:
```console
$ ls /home/mzasso/.nvm/versions/node/v8.8.0/lib/node_modules/node-core-utils/
bin  lib  LICENSE  node_modules  package.json  queries  README.md
```

There is no `steps` directory in there.

**Comment by Tiriel** [comment]
Thanks!

There indeed seems to be a problem, at least with Node v8.4. Is that the version you use?
There is also an error with v8.9, but a different one...
Investigating ASAP.

**Comment by targos** [comment]
I'm using node 8.8.0

**Comment by Tiriel** [comment]
Okay!

Well, this error occurs at least from 8.4 to 8.8 then, and we have another one, though probably related, with 8.9.

As said, I'll check ASAP if someone doesn't do it sooner (currently at work)

**Comment by targos** [comment]
I found the fix. PR incoming.

**Comment by targos** [comment]
https://github.com/joyeecheung/node-core-utils/pull/91
